spring.application.name=sb-ecom
spring.mvc.pathmatch.matching-strategy=ant_path_matcher


spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true


spring.app.jwtSecret=mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
spring.app.jwtExpirationMs=3600000
spring.ecom.app.jwtCookieName=springBootEcom
spring.app.jwtSecure=${JWT_SECURE}
spring.app.jwtSameSite=${JWT_SAME_SITE}
spring.app.jwtHttpOnly=${JWT_HTTP_ONLY}



#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.com.ecommerce.project=DEBUG


# Needed if you are using elastic beanstalk
#server.port=5000
frontend.url=${FRONTEND_URL}
# ==========================================
# STORAGE CONFIGURATION
# ==========================================

# 1. LOCAL STORAGE (Uncomment for testing/dev)
project.image=images/
image.base.url=http://localhost:8080/images

# 2. CLOUDINARY STORAGE (Uncomment for production)
# To enable Cloudinary, uncomment all 3 lines BELOW
cloudinary.cloud_name=${CLOUDINARY_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

# Note: If Cloudinary properties are commented out, 
# the system defaults to Local Storage automatically.
# ==========================================
